export const GET_BRAND_INPUT = "GET_BRAND_INPUT";
export const IS_LOAD_BRAND = "IS_LOAD_BRAND";
export const IS_SUCCESS_BRAND = "IS_SUCCESS_BRAND";
export const GET_BRAND_LIST = "GET_BRAND_LIST";
export const IS_LOAD_BRAND_LIST = "IS_LOAD_BRAND_LIST";
export const IS_BRAND_DELETED = "IS_BRAND_DELETED";
export const SET_BRAND_UPDATED = "SET_BRAND_UPDATED";
